### PR TITLE
Fix utp host/port info

### PR DESCRIPTION
**Pull request by pfrazee**
Depends on https://github.com/mafintosh/utp-native/pull/23 to be published (I assumed it will be published 1.7.0)

### CODE REVIEW

**Comment by mafintosh** [comment]
We need to drop 0.12, 0.10 since deps don't support those

**Comment by mafintosh** [comment]
... on travis

**Comment by pfrazee** [comment]
ok cool

**Comment by mafintosh** [comment]
Released as 5.1.0

**Pull request merged**
